### ISSUE TITLE
User Authentication

### ISSUE THREAD

**Issue by Bennyz811** [Bennyz811/Velp#2]
Allow user to sign up/log in and retain page when reload

**Comment by m1010j** [comment]
- [ ] You should put in some more work into styling. Try to make it look as close to the real thing as possible.

- [ ] You don't need to have the button to sign in with Facebook.

- [ ]  The error that pops up when you validate the email address on the sign up form looks great. Can you render all of your errors at the top of the page that way?

**Comment by m1010j** [comment]
- [ ] There's something odd happening to your sign-up button when I hover over the log-in button.
